services:
  postgres:
    image: postgres:17
    container_name: paperless_postgres_db
    environment:
      POSTGRES_DB: paperless_db
      POSTGRES_USER: paperless_user
      POSTGRES_PASSWORD: paperless_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless_user -d paperless_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: paperless_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5

  ocr-worker:
    build: ./workers/ocr-worker
    container_name: paperless_ocr_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      MINIO_URL: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      API_URL: http://paperless-rest-api:8080

  genai-worker:
    build: ./workers/genai-worker
    container_name: paperless_genai_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      paperless-rest-api:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      API_URL: http://paperless-rest-api:8080
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

  minio:
    image: minio/minio:latest
    container_name: paperless_minio
    ports:
      - "9000:9000" # API Port
      - "9090:9090" # Console Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  paperless-rest-api:
    build: ./backend
    container_name: paperless_rest_api
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/paperless_db
      DB_USER: paperless_user
      DB_PASSWORD: paperless_password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
      ELASTIC_URL: http://elasticsearch:9200

  paperless-ui:
    build: ./frontend
    container_name: paperless_ui

  nginx:
    image: nginx:latest
    container_name: paperless_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paperless-rest-api
      - paperless-ui
  
  adminer:
    image: adminer
    container_name: paperless_adminer
    ports:
      - "9091:8080"
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: paperless_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  postgres_data:
  minio_data:
  es_data:
